name: HungI Zzao
markdown: redcarpet
highlighter: pygments
url: "http://zzao.im/blog"
baseurl: "/blog"
timezone: "Asia/Shanghai"
permalink: "/post/:title.html"
kramdown:
  input: GFM
gems:
  # - jekyll-sitemap
  # - jekyll-mentions
navs:

  - name: "About"
    url: "/about.html"
  - name: "Links"
    url: "/Links.html"




defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
